#pragma once 

//overrides
#undef TAPPING_TOGGLE
#define TAPPING_TOGGLE 3
#define TAPPING_TERM 200
#define LEADER_TIMEOUT 300
#define LEADER_PER_KEY_TIMING
#define RGB_MATRIX_KEYPRESSES
#define RGB_MATRIX_FRAMEBUFFER_EFFECTS
/* #define DISABLE_RGB_MATRIX_DIGITAL_RAIN //broken until PR(#5811) merges */

#undef RGBLED_NUM
#define  RGBLED_NUM 7
