#pragma once

//overrides
#undef TAPPING_TOGGLE
#define TAPPING_TOGGLE 3
#define TAPPING_TERM 200
#define LEADER_TIMEOUT 250
#define LEADER_PER_KEY_TIMING
#define RGB_MATRIX_KEYPRESSES
#define USB_LED_NUM_LOCK_SCANCODE 7 //KC_7
